
substitutions:
  name: "under-bed-lighting"
  slug: "under_bed_lighting"
  friendly_name: "Under Bed Lighting"

  pin_led_enable: GPIO0
  pin_led1: GPIO2
  pin_led2: GPIO8
  pin_led3: GPIO5

  pin_pir1: GPIO4
  pin_pir2: GPIO3
  pin_pir3: GPIO1
  pin_pir4: GPIO10

  # get secrets from secrets.yaml
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  api_key: !secret api_key
  ap_password: !secret ap_password

packages:
  # Standard-ish ESPHome components for all devices
  board: !include ../packages/boards/esp32_c3_supermini.yaml
  base: !include ../packages/base/base.yaml
  diagnostics: !include ../packages/base/diagnostics.yaml

  # Feature packages for this device
  led_pwm: !include ../packages/features/led_pwm.yaml

  # This must be last because it contains debug components that should be overridden by other packages if needed
  debug: !include ../packages/base/debug.yaml

